### ISSUE TITLE
骚扰我几年了吧

### ISSUE THREAD

**Issue by Naville** [Chandler-Song/Jobs#2]
我记得几年前就收到过你群发的招聘这个招聘那个的邮件还有末尾的elp-consulting。上次我还认真回了个不想做iOS，又来？

爬

**Comment by Naville** [comment]
> Hi，我是Chandler，Github看到您在做iOS的项目，

真就基于关键词搜索Spam嗷

> 最近我在帮一家国际知名科技公司音视频会议团队招聘iOS移动端技术专家，

我估摸着没人想理公司名字和薪酬待遇都不写的群发骚扰招聘广告

> 音视频会议产品上半年International User增长到6倍

我大学写的作业写完给几个老外试用，一个小时International User就从1增长到了20，20倍增长

> 团队正在快速发展中，

也就是说现在没几个人

^#如果您在看新机会的话，可以留个电话或者微信具体给您详细介绍下，期待您的回复，Thanks~~      详细职位JD请看Github: https://github.com/Chandler-Song/Jobs/blob/master/iOS_JD.md

**Comment by Chandler-Song** [comment]
如有打扰，敬请见谅

**Comment by Chandler-Song** [comment]
> > Hi，我是Chandler，Github看到您在做iOS的项目，
> 
> 真就基于关键词搜索Spam嗷
> 
> > 最近我在帮一家国际知名科技公司音视频会议团队招聘iOS移动端技术专家，
> 
> 我估摸着没人想理公司名字和薪酬待遇都不写的群发骚扰招聘广告
> 
> > 音视频会议产品上半年International User增长到6倍
> 
> 我大学写的作业写完给几个老外试用，一个小时International User就从1增长到了20，20倍增长
> 
> > 团队正在快速发展中，
> 
> 也就是说现在没几个人
> 
> ^#如果您在看新机会的话，可以留个电话或者微信具体给您详细介绍下，期待您的回复，Thanks~~ 详细职位JD请看Github: https://github.com/Chandler-Song/Jobs/blob/master/iOS_JD.md

**Comment by HatsuneMikuV** [comment]
看完你们的回复，我想了想，真是难为 @Chandler-Song 你了，为了招人，还要学习git知识

**Comment by xingheng** [comment]
+1

没有JD就算了，连个坐标都没有你招个毛线啊！还是说你把你个人跟人家招聘平台划等号了？
